name: CI

on: [push]

jobs:

  test:

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Setup rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}

    - name: Setup sqlite
      run: sudo apt-get install libsqlite3 libsqlite3-dev

    - name: Setup diesel
      run: cargo install diesel_cli --force --no-default-features --features sqlite

    - name: Checkout
      uses: actions/checkout@master

    - name: Run migrations
      env:
        DATABASE_URL: "var/db.sqlite"
      run: make db

    - name: Run tests
      env:
        DATABASE_URL: "var/db.sqlite"
      run: make test
